project_name: "dockercoins"
namespace: "dockercoins"
apiServer: "https://akshelaw-78c8fea0.hcp.northeurope.azmk8s.io:443"
apiServerQa: "https://akshelaw-78c8fea0.hcp.northeurope.azmk8s.io:443"
apiServerProd: "https://akshelaw-78c8fea0.hcp.northeurope.azmk8s.io:443"
